config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
   devise_for :users
    root to: "homes#index"
    get "/event", to: "events#index"
    get "/booking", to: "tickets#index"
    resources :homes
    resources :searchs
    resources :tickets do
      get "Getvalue", action: "loadData"
    end

    namespace :admin do
    resources :homes do
      get "delete"
    end
    resources :movies do
      get "delete"
    end
    resources :schedules do
      get "delete"
      get "Getdata", action: "getdataTime"
    end
    resources :cinemarooms do
      get "delete"
    end
    resources :seats do
      get "delete"
      get "seatGet", action: "cinemaroom_getdata"
    end
    resources :users do
      get "delete"
    end
    resources :studios do
      get "delete"
    end
    resources :movietypes do
      get "delete"
    end
    resources :movies_movietypes do
      get "delete"
    end
    resources :schedule_times do
      get "delete"
    end
    end

  end
end

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <a class="navbar-brand" href="index.html"><%= t "title_admin" %></a>
  </div>
  <%= render "layouts/admin/headerMenu" %>
  <%= render "layouts/admin/leftMenu" %>
</nav>

app/views/layouts/admin/_headerMenu.html.erb
<ul class="nav navbar-top-links navbar-right">
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
    </a>
    <ul class="dropdown-menu dropdown-user">
      <li>
        <%= link_to root_path do %>
          <i class="fa fa-home fa-fw"></i><%= t "home" %>
        <% end %>
      </li>
      <li class="divider"></li>
      <li>
        <%= link_to destroy_user_session_path, :method => "delete" do %>
          <i class="fa fa-sign-out fa-fw"></i> <%= t "logout" %>
        <% end %>
      </li>
    </ul>
  </li>
</ul>

app/views/layouts/admin/_leftMenu.html.erb
<div class="navbar-default sidebar" role="navigation">
  <div class="sidebar-nav navbar-collapse">
    <ul class="nav in" id="side-menu">
      <li>
        <%= link_to admin_users_path do %>
          <i class="fa fa-dashboard fa-fw"></i> <%= t "menu.user" %>
        <% end %>
      </li>
       <li>
        <%= link_to admin_studios_path do %>
          <i class="fa fa-dashboard fa-fw"></i> <%= t "menu.studio" %>
        <% end %>
      </li>
      <li>
        <%= link_to admin_seats_path do %>
          <i class="fa fa-dashboard fa-fw"></i> <%= t "menu.seat" %>
        <% end %>
      </li>
      <li>
        <%= link_to admin_schedules_path do %>
          <i class="fa fa-dashboard fa-fw"></i> <%= t "menu.schedule" %>
        <% end %>
      </li>
      <li>
        <%= link_to admin_movies_path do %>
          <i class="fa fa-dashboard fa-fw"></i> <%= t "menu.movie" %>
        <% end %>
      </li>
      <li>
        <%= link_to admin_movies_movietypes_path do %>
          <i class="fa fa-dashboard fa-fw"></i> <%= t "menu.movies_movietype" %>
        <% end %>
      </li>
      <li>
        <%= link_to admin_movietypes_path do %>
          <i class="fa fa-dashboard fa-fw"></i> <%= t "menu.movie_type" %>
          <% end %>
      </li>
      <li>
        <%= link_to admin_schedule_times_path do %>
          <i class="fa fa-dashboard fa-fw"></i> <%= t "menu.schedule_time" %>
          <% end %>
      </li>
      <li>
        <%= link_to admin_cinemarooms_path do %>
          <i class="fa fa-dashboard fa-fw"></i> <%= t "menu.cinemaroom" %>
          <% end %>
      </li>
    </ul>
  </div>
</div>