config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
   devise_for :users
    root to: "homes#index"
    get "/event", to: "events#index"
    get "/booking", to: "tickets#index"
    resources :homes
    resources :searchs
    resources :tickets do
      get "Getvalue", action: "loadData"
    end

    namespace :admin do
    resources :homes do
      get "delete"
    end
    resources :movies do
      get "delete"
    end
    resources :schedules do
      get "delete"
      get "Getdata", action: "getdataTime"
    end
    resources :cinemarooms do
      get "delete"
    end
    resources :seats do
      get "delete"
      get "seatGet", action: "cinemaroom_getdata"
    end
    resources :users do
      get "delete"
    end
    resources :studios do
      get "delete"
    end
    resources :movietypes do
      get "delete"
    end
    resources :movies_movietypes do
      get "delete"
    end
    resources :schedule_times do
      get "delete"
    end
    end

  end
end

app/controllers/admin/movietypes_controller.rb
class Admin::MovietypesController < Admin::ApplicationController
  before_action :movietype_read, except: %W(index create new)
  def index
  	@movietypes = Movietype.all.where(is_delete: false)
  end

  def create
    @movietype = Movietype.new movietype_params
    if @movietype.save
     flash[:success] = t "new_suscess"
      redirect_to admin_movietypes_path
    else
      render :new
    end
  end

  def new
    @movietype = Movietype.new
  end

  def edit
    
  end

  def update
    if @movietype.update_attributes movietype_params
     flash[:success] = t "update_suscess"
      redirect_to admin_movietypes_path
    else
      render :edit
    end
  end

  def delete
     @movietype_d = Movietype.find_by id: params[:movietype_id]
  end

  def destroy
     @movietype_d = Movietype.find_by id: params[:id]
     if @movietype_d.update_attributes is_delete:true
      flash[:success] = t "delete_suscess"
      redirect_to admin_movietypes_path
    else
      render :edit
    end
  end


  private

  def movietype_params
  	params.require(:movietype).permit :name, :status
  end

  def movietype_read
    @movietype = Movietype.find_by id: params[:id]
  end
end

app/views/admin/movietypes/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3><%= t "delete" %></h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  <%= t "sure_delete" %><b><%= @movietype_d.name %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to t("yes_delete"), admin_movietype_path(@movietype_d), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to t("no_delete"), "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/admin/movietypes/_edit.html.erb
<% provide :button_text, t("save_change") %>
<% provide :text_head, "Editing #{@movietype.name}" %>
<%= render "form" %>

app/views/admin/movietypes/_form.html.erb
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%= label_tag yield(:text_head)%></h4>
      <ul class="errors">
      </ul>
      </div>
      <div class="modal-body">
	    <%= form_for [:admin, @movietype], remote: true do |f| %>
        <%= render "shared/error_messages", :target => @movietype %>
			<div class="form-group">
			  <%= f.label :name %>
			  <%= f.text_field :name, class: "form-control" %>
			</div>

			<%= f.label :status %>
			<div class="form-group">
			  <%= label :status, t("action") %>
			  <%= f.radio_button :status, "1",:checked => true %>
			  <%= label :status, t("unaction") %>
			  <%= f.radio_button :status, "0" %>
			</div>

			<div class="modal-footer">
		   		<%= f.submit yield(:button_text), class: "btn btn-primary" %>
		 	    <%= link_to "Cancel", "#", class: "btn btn-default", data: {dismiss: "modal"} %>
			</div>
			<% end %>
			</div>
    </div>
  </div>

app/views/admin/movietypes/_headerTable.html.erb
<th class="text-center"><%= t "stt" %></th>
<th class="text-center"><%= t "Movietypes.name" %></th>
<th class="text-center"><%= t "Movietypes.status" %></th>
<th class="text-center" style = "width: 160px;"><%= t ".action" %></th>

app/views/admin/movietypes/_index.html.erb
 <% @movietypes.each_with_index do |item, index| %>
  <tr>
    <td class="text-center"><%= Index index %></td>
    <td><%= item.name %></td>
    <td class="text-center"><%= item.status %></td>
    <td>
     <%= link_to t("edit"), edit_admin_movietype_path(item), remote: true, class:"btn btn-info" %>
    <%= link_to t("delete"), admin_movietype_delete_path(item), remote: true, class:"btn btn-danger" %>
    </td>
  </tr>
<% end %>

app/views/admin/movietypes/_new.html.erb
<% provide :button_text, t("save_change") %>
<% provide :text_head, t("add") %>
<%= render "form" %>

app/views/admin/movietypes/_save.js.erb
$("ul.errors").html("")
<% if @movietype.errors.any? %>
  <% @movietype.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $("#product-modal").modal("hide")
<% end %>

app/views/admin/movietypes/delete.js.erb
$("#product-modal").html('<%= j render(partial: "admin/movietypes/delete") %>')
$("#product-modal").modal("show")

app/views/admin/movietypes/edit.js.erb
$("#product-modal").html("<%= j render(partial: "admin/movietypes/edit") %>")
$("#product-modal").modal("show")

app/views/admin/movietypes/index.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <%= link_to t("dashboard") %>
  </li>
  <li class="breadcrumb-item active"><%= t "menu.movie_type" %></li>
  <%= link_to t("add"), new_admin_movietype_path,remote: true, class: "btn btn-primary" %>
</ol>
<div class="card mb-3">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
        <tr>
          <%= render "headerTable" %>
        </tr>
        </thead>
        <tbody>
          <%= render "index" %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div id="product-modal" class="modal fade" role= "dialog"></div>

app/views/admin/movietypes/new.js.erb
$("#product-modal").html('<%= j render(partial: "admin/studios/new") %>')
$("#product-modal").modal("show")