config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
   devise_for :users
    root to: "homes#index"
    get "/event", to: "events#index"
    get "/booking", to: "tickets#index"
    resources :homes
    resources :searchs
    resources :tickets do
      get "Getvalue", action: "loadData"
    end

    namespace :admin do
    resources :homes do
      get "delete"
    end
    resources :movies do
      get "delete"
    end
    resources :schedules do
      get "delete"
      get "Getdata", action: "getdataTime"
    end
    resources :cinemarooms do
      get "delete"
    end
    resources :seats do
      get "delete"
      get "seatGet", action: "cinemaroom_getdata"
    end
    resources :users do
      get "delete"
    end
    resources :studios do
      get "delete"
    end
    resources :movietypes do
      get "delete"
    end
    resources :movies_movietypes do
      get "delete"
    end
    resources :schedule_times do
      get "delete"
    end
    end

  end
end

app/models/schedule_time.rb
class ScheduleTime < ApplicationRecord
  has_many :schedules, dependent: :destroy
  VALID_TIME_REGEX = /\A([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]\z/i
  validates :start_time, presence: true, format: {with: VALID_TIME_REGEX}
  validates :end_time, presence: true, format: {with: VALID_TIME_REGEX}
end

app/controllers/admin/schedule_times_controller.rb
class Admin::ScheduleTimesController < Admin::ApplicationController
  before_action :scheduleTime_read, except: %W(index create new)
  before_action :search_duplicates, only: %W(create update)
  def index
  	@schedule_times = ScheduleTime.all.where(is_delete: false)
  end

  def create
    if @schedule_date.empty? & check_time?
      if check_time? & @schedule_time.save
        flash[:success] = t "new_suscess"
        redirect_to admin_schedule_times_path
      else
        flash[:danger] = t "danger"
        render :new
      end
    else
      if !check_time?
        flash[:danger] =  t "time_used"
      else
        flash[:danger] =  t "data_used"
      end
      redirect_to admin_schedule_times_path
    end
  end

  def new
    @schedule_time = ScheduleTime.new
  end

  def edit
    
  end

  def update
    if @schedule_time.update_attributes scheduleTime_param
      flash[:success] = t "update_suscess"
      redirect_to admin_schedule_times_path
    else
      flash[:danger] = t "danger"
      render :edit
    end
  end

  def delete
    @schedule_time_d = ScheduleTime.find_by id: params[:schedule_time_id]
  end

  def destroy
     @schedule_time_d = ScheduleTime.find_by id: params[:id]
     if @schedule_time_d.update_attributes is_delete:true
      flash[:success] = t "delete_suscess"
      redirect_to admin_schedule_times_path
    else
      flash[:danger] = t "danger"
      render :edit
    end
  end

  private

  def scheduleTime_param
  	params.require(:schedule_time).permit :start_time, :end_time, :status
  end

  def scheduleTime_read
    @schedule_time = ScheduleTime.find_by id: params[:id]
  end

  def check_time?
    return @schedule_time.start_time != @schedule_time.end_time && @schedule_time.start_time.to_i < @schedule_time.end_time.to_i
  end

  def search_duplicates
    @schedule_time = ScheduleTime.new scheduleTime_param
    @schedule_date = ScheduleTime.select("*")
      .where("schedule_times.start_time=? and schedule_times.end_time=? ", @schedule_time.start_time, @schedule_time.end_time)
  end
end

app/views/admin/schedule_times/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3><%= t "delete" %></h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  <%= t "sure_delete" %>
  </div>
  <div class="modal-footer">
    <%= link_to t("yes_delete"), admin_schedule_time_path(@schedule_time_d), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to t("no_delete"), "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/admin/schedule_times/_form.html.erb
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%= label_tag yield(:text_head)%></h4>
      </div>
      <div class="modal-body">
		<%= form_for [:admin, @schedule_time], remote: true do |f| %>
        <%= render "shared/error_messages", :target => @schedule_time %>
			<div class="form-group">
			  <%= f.label :start_time %>
			  <%= f.text_field :start_time, class: "form-control" %>
			</div>

			<div class="form-group">
			  <%= f.label :end_time %>
			  <%= f.text_field :end_time ,class: "form-control" %>
			</div>

			<%= f.label :status %>
			<div class="form-group">
			  <%= label :status, t("action") %>
			  <%= f.radio_button :status, "1",:checked => true %>
			  <%= label :status, t("unaction") %>
			  <%= f.radio_button :status, "0" %>
			</div>

			<div class="modal-footer">
		   		<%= f.submit yield(:button_text), class: "btn btn-primary" %>
		 	    <%= link_to "Cancel", "#", class: "btn btn-default", data: {dismiss: "modal"} %>
			</div>
			<% end %>
			</div>
    </div>
  </div>

app/views/admin/schedule_times/_headerTable.html.erb
<th class="text-center" ><%= t "stt" %></th>
<th class="text-center" ><%= t "Schedule_time.start_time" %></th>
<th class="text-center" ><%= t "Schedule_time.end_time" %></th>
<th class="text-center" ><%= t "status" %></th>
<th class="text-center"  style="width: 150px"><%= t ".action" %></th>

app/views/admin/schedule_times/_index.html.erb
 <% @schedule_times.each_with_index do |item, index| %>
  <tr>
    <td class="text-center" ><%= Index index %></td>
    <td class="text-center" ><%= item.start_time %></td>
    <td class="text-center" ><%= item.end_time %></td>
    <td class="text-center" ><%= item.status %></td>
    <td>
    <%#= link_to t("edit"), edit_admin_schedule_time_path(item), remote: true, class:"btn btn-info" %>
    <%= link_to t("delete"), admin_schedule_time_delete_path(item), remote: true, class:"btn btn-danger" %>
    </td>
  </tr>
<% end %>

app/views/admin/schedule_times/_new.html.erb
<% provide :button_text, t("save_change") %>
<% provide :text_head, t("add") %>
<%= render "form" %>

app/views/admin/schedule_times/_save.js.erb
$(".errors").html("")
<% if @schedule_time.errors.any? %>
  <% @schedule_time.errors.full_messages.each do |message| %>
    $(".errors").html("<%= message.html_safe %>")
  <% end %>
<% else %>
  $("#product-modal").modal("hide")
<% end %>

app/views/admin/schedule_times/delete.js.erb
$("#product-modal").html('<%= j render(partial: "admin/schedule_times/delete") %>')
$("#product-modal").modal("show")

app/views/admin/schedule_times/edit.js.erb
$("#product-modal").html("<%= j render(partial: "admin/schedule_times/edit") %>")
$("#product-modal").modal("show")

app/views/admin/schedule_times/index.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <%= link_to t("dashboard") %>
  </li>
  <li class="breadcrumb-item active"><%= t "menu.schedule_time" %></li>
   <%= link_to t("add"), new_admin_schedule_time_path,remote: true, class: "btn btn-primary" %>
</ol>
<div class="card mb-3">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
        <tr>
          <%= render "headerTable" %>
        </tr>
        </thead>
        <tbody>
           <%= render "index" %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div id="product-modal" class="modal fade" role= "dialog"></div>

app/views/admin/schedule_times/new.js.erb
$("#product-modal").html('<%= j render(partial: "admin/schedule_times/new") %>')
$("#product-modal").modal("show")