config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
   devise_for :users
    root to: "homes#index"
    get "/event", to: "events#index"
    get "/booking", to: "tickets#index"
    resources :homes
    resources :searchs
    resources :tickets do
      get "Getvalue", action: "loadData"
    end

    namespace :admin do
    resources :homes do
      get "delete"
    end
    resources :movies do
      get "delete"
    end
    resources :schedules do
      get "delete"
      get "Getdata", action: "getdataTime"
    end
    resources :cinemarooms do
      get "delete"
    end
    resources :seats do
      get "delete"
      get "seatGet", action: "cinemaroom_getdata"
    end
    resources :users do
      get "delete"
    end
    resources :studios do
      get "delete"
    end
    resources :movietypes do
      get "delete"
    end
    resources :movies_movietypes do
      get "delete"
    end
    resources :schedule_times do
      get "delete"
    end
    end

  end
end

app/models/studio.rb
class Studio < ApplicationRecord
  has_many :movies, dependent: :destroy
  scope :sort_alpha, -> do
  	Movie.joins(:studio).select("*, count(movies.id)")
  	.group("studio_id").limit(3)
  end
  validates :name, presence: true, uniqueness: true
   #format: {with: /\A[a-zA-Z]+\z/}
end

app/controllers/admin/studios_controller.rb
class Admin::StudiosController < Admin::ApplicationController
  before_action :studio_read, except: %w(index, create, new)
  def index
  	@studios = Studio.all.where(is_delete: false)
  end

  def create
    @studio = Studio.new studio_params
    if @studio.save
      flash[:success] = t "new_suscess"
      redirect_to admin_studios_path
    else
      render :new
    end
     respond_to do |format|
       format.js
     end
  end

  def new
    @studio = Studio.new
  end

  def edit
  end

  def update
    if @studio.update_attributes studio_params
      flash[:success] = t "update_suscess"
      redirect_to admin_studios_path
    else
      render :edit
    end
  end

  def delete
    @studio_d = Studio.find_by id: params[:studio_id]
  end

  def destroy
    @studio_des = Studio.find_by id: params[:id]
    if @studio_des.update_attributes is_delete:true
      flash[:success] = t "delete_suscess"
      redirect_to admin_studios_path
    else
      render :edit
    end
  end

  private

  def studio_params
  	params.require(:studio).permit :name, :status
  end

  def studio_read
    @studio = Studio.find_by id: params[:id]
  end
end

app/views/admin/studios/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3><%= t "delete" %></h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  <%= t "sure_delete" %><b><%= @studio_d.name %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to t("yes_delete"), admin_studio_path(@studio_d), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to t("no_delete"), "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/admin/studios/_edit.html.erb
<% provide :button_text, t("save_change") %>
<% provide :text_head, "Editing #{@studio.name}" %>
<%= render "form" %>

app/views/admin/studios/_form.html.erb
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%= label_tag yield(:text_head)%></h4>
      </div>
      <div class="modal-body">
        <%= form_for [:admin, @studio], remote: true do |f| %>
        <%= render "shared/error_messages", :target => @studio %>
			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class: "form-control" %>
			</div>

				<%= f.label :status %>
			<div class="form-group">
				<%= label :status, t("action") %>
				<%= f.radio_button :status, "1",:checked => true %>
				<%= label :status, t("unaction") %>
				<%= f.radio_button :status, "0" %>
			</div>
			<div class="modal-footer">
		   		<%= f.submit yield(:button_text), class: "btn btn-primary" %>
		 	    <%= link_to "Cancel", "#", class: "btn btn-default", data: {dismiss: "modal"} %>
			</div>
		<% end %>
      </div>
    </div>
  </div>

app/views/admin/studios/_headerTable.html.erb
<th class="text-center"><%= t "stt" %></th>
<th class="text-center"><%= t "studios.name" %></th>
<th class="text-center"><%= t "studios.status" %></th>
<th class="text-center" style="width:160px"><%= t ".action" %></th>

app/views/admin/studios/_index.html.erb
<% @studios.each_with_index do |item, index| %>
<tr>
  <td class="text-center" ><%= Index index %></td>
  <td class= "text-left"><%= item.name %></td>
  <td class="text-center"><%= item.status %></td>
  <td>
    <%= link_to t("edit"), edit_admin_studio_path(item), remote: true, class:"btn btn-info" %>
    <%= link_to t("delete"), admin_studio_delete_path(item), remote: true, class:"btn btn-danger" %>
  </td>
</tr>
<% end %>

app/views/admin/studios/_new.html.erb
<% provide :button_text, t("save_change") %>
<% provide :text_head, t("add") %>
<%= render "form" %>

app/views/admin/studios/_save.js.erb
$(".errors").html("")
<% if @studio.errors.any? %>
  <% @studio.errors.full_messages.each do |message| %>
    $(".errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $("#product-modal").modal("hide")
<% end %>

app/views/admin/studios/delete.js.erb
$("#product-modal").html('<%= j render(partial: "admin/studios/delete") %>')
$("#product-modal").modal("show")

app/views/admin/studios/edit.js.erb
$("#product-modal").html("<%= j render(partial: "admin/studios/edit") %>")
$("#product-modal").modal("show")

app/views/admin/studios/index.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <%= link_to t("dashboard") %>
  </li>
  <li class="breadcrumb-item active"><%= t "menu.studio" %></li>
   <%= link_to t("add"), new_admin_studio_path, remote: true, class: "btn btn-primary" %>
</ol>
<div class="card mb-3">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
        <tr>
          <%= render "headerTable" %>
        </tr>
        </thead>
        <tbody>
          <%= render "index" %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div id="product-modal" class="modal fade" role= "dialog"></div>

app/views/admin/studios/new.js.erb
$("#product-modal").html('<%= j render(partial: "admin/studios/new") %>')
$("#product-modal").modal("show")

app/views/admin/studios/update.js.erb
<%= render "save" %>